#!/bin/ansible-playbook

---

- hosts: localhost
  tags: [ "git" ]
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    repo_path: "{{ home_path }}/.dotfiles"
    user_id: "{{ ansible_user_id }}"
  tasks:
  
  - name: "Install required packages"
    become: yes
    package:
      name:
      - vim
      - tmux
      - zsh
      state: latest

  - name: Change user shell to zsh 
    become: yes
    user:
      name: "{{ user_id }}"
      shell: /bin/zsh

  - name: "Clone git repository in {{ repo_path }}"
    git:
      repo: "https://github.com/benjaminBoboul/.dotfiles.git"
      dest: "{{ repo_path }}"
      clone: yes
      update: yes

  - name: "Backup configuration files"
    copy:
      src: "{{ repo_path }}/{{ item }}"
      dest: "{{ home_path }}/{{ item }}"
      backup: yes
      backup_file: "{{ home_path }}/{{ item }}.pre-dotfiles"
    with_items:
    - .zshrc
    - .vimrc
    - .tmux.conf
      
