
on:
  pull_request:
    branches:
      - master

name: validate

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: >2-
          ansible-pull
          --url https://github.com/import-benjamin/.dotfiles.git
          --checkout {{ github.head_ref}}
          --extra-vars "config_version={{ github.head_ref }}"
          --inventory localhost,
          --connection local
          --ask-become-pass
          playbook.yml

